# Generated by Django 3.2.4 on 2021-07-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomInfo',
            new_name='Room',
        ),
        migrations.CreateModel(
            name='RoomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('platform', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
