# Generated by Django 3.2.4 on 2021-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210711_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='link',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
