# Generated by Django 3.2.4 on 2021-09-19 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rename_user_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='platform',
        ),
        migrations.AddField(
            model_name='roomlink',
            name='android',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomlink',
            name='ios',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomlink',
            name='web',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
