# Generated by Django 3.2.4 on 2021-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210919_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlink',
            name='android',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='roomlink',
            name='ios',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='roomlink',
            name='web',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
