# Generated by Django 3.2.4 on 2021-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20210919_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
