# Generated by Django 3.2.4 on 2021-09-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_hello_profile_number'),
        ('rooms', '0012_roomlink_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_rooms', to='accounts.profile'),
        ),
    ]
