# Generated by Django 3.2.4 on 2021-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_hello_profile_number'),
        ('rooms', '0014_alter_roomlink_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlink',
            name='users',
            field=models.ManyToManyField(default=None, related_name='links', to='accounts.Profile'),
        ),
    ]
