# Generated by Django 3.2.4 on 2021-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_hello_profile_number'),
        ('rooms', '0016_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='display_name',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='roomlink',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='roomlink',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='mylinks', to='accounts.Profile'),
        ),
    ]
