# Generated by Django 3.2.4 on 2021-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_auto_20210920_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRegData',
            fields=[
                ('name', models.CharField(default=None, max_length=70, primary_key=True, serialize=False)),
                ('data', models.TextField(default=None)),
            ],
        ),
    ]
