# Generated by Django 3.2.4 on 2021-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_linkregdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRegularData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('data', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='LinkRegData',
        ),
    ]
