# Generated by Django 3.2.4 on 2021-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20210920_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='sought',
            field=models.BooleanField(default=False),
        ),
    ]
