# Generated by Django 3.2.4 on 2021-09-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_roomlink_sought'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuxSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default=None)),
                ('main_silo', models.ManyToManyField(default=None, related_name='data', to='rooms.MainSilo')),
            ],
        ),
        migrations.AddField(
            model_name='roomlink',
            name='main_silo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_link', to='rooms.auxsilo'),
        ),
    ]
