# Generated by Django 3.2.4 on 2021-09-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_auto_20210928_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxsilo',
            name='main_silo',
        ),
        migrations.AddField(
            model_name='auxsilo',
            name='main_silo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='rooms.mainsilo'),
        ),
    ]
