# Generated by Django 3.2.4 on 2021-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_alter_roomlink_main_silo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxsilo',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
