# Generated by Django 3.2.4 on 2021-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_auxsilo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxsilo',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
