# Generated by Django 3.2.4 on 2021-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_alter_auxsilo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='call_time',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
