# Generated by Django 3.2.4 on 2021-11-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_hello_profile_number'),
        ('rooms', '0030_roomlink_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='buyers',
            field=models.ManyToManyField(blank=True, default=None, related_name='mybuyers', to='accounts.Profile'),
        ),
    ]
