# Generated by Django 3.2.4 on 2021-11-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0033_auto_20211117_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxsilo',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
