# Generated by Django 3.2.4 on 2021-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0034_auxsilo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomlink',
            name='android',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='ios',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='main_silo',
        ),
        migrations.RemoveField(
            model_name='roomlink',
            name='web',
        ),
        migrations.AddField(
            model_name='roomlink',
            name='fields',
            field=models.TextField(default=None, null=True),
        ),
    ]
