# Generated by Django 3.2.4 on 2021-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0036_auxsilo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxsilo',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
