# Generated by Django 3.2.4 on 2021-12-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0037_alter_auxsilo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxsilo',
            name='data_hash',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
