# Generated by Django 3.2.4 on 2021-12-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0038_auxsilo_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='off_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
