# Generated by Django 3.2.4 on 2021-12-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0040_roomlink_data_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomlink',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
